# Generated by Django 6.0.6 on 2026-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionbatch',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='extractionsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
