# Generated by Django 6.0.6 on 2026-08-17 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnupdatedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='processing', max_length=20)),
                ('include_consumer', models.BooleanField(default=True)),
                ('include_commercial', models.BooleanField(default=True)),
                ('reporting_month', models.CharField(default='', help_text='e.g. 2026-07', max_length=7)),
                ('last_period_num', models.CharField(default='', help_text='e.g. 20260731', max_length=8)),
                ('cutoff_date', models.CharField(default='', help_text='e.g. 2026-08-01', max_length=10)),
                ('master_zip', models.FileField(blank=True, null=True, upload_to='unupdated/zips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unupdated_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnupdatedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField()),
                ('subscriber_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20)),
                ('consumer_rows', models.IntegerField(default=0)),
                ('commercial_rows', models.IntegerField(default=0)),
                ('subscriber_file', models.FileField(blank=True, null=True, upload_to='unupdated/reports/')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='unupdated.unupdatedbatch')),
            ],
            options={
                'ordering': ['subscriber_name'],
            },
        ),
    ]
