# Generated by Django 6.0.6 on 2026-08-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unupdated', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unupdatedbatch',
            name='master_zip',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='unupdated/zips/'),
        ),
        migrations.AlterField(
            model_name='unupdatedsession',
            name='subscriber_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='unupdated/reports/'),
        ),
    ]
