# Generated by Django 6.0.6 on 2026-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unupdated', '0002_alter_unupdatedbatch_master_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unupdatedsession',
            name='is_file_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unupdatedsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_upload', 'Awaiting Upload'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
