# Generated by Django 6.0.6 on 2026-09-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unupdated', '0003_unupdatedsession_is_file_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unupdatedsession',
            name='commercial_max_period',
            field=models.CharField(blank=True, default='', help_text='e.g. 20260731', max_length=8),
        ),
        migrations.AddField(
            model_name='unupdatedsession',
            name='consumer_max_period',
            field=models.CharField(blank=True, default='', help_text='e.g. 20260731', max_length=8),
        ),
    ]
