# Generated by Django 5.2.5 on 2026-02-08 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('overdue_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('days_in_arrears', models.IntegerField(blank=True, null=True)),
                ('loan_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('account_status_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_session_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cleaned_data',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_mapping', 'Pending Mapping'), ('processed', 'Processed'), ('uploaded', 'Uploaded to SQL'), ('error', 'Error')], default='pending_mapping', max_length=20)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_uploaded', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_header', models.CharField(max_length=255)),
                ('target_column', models.CharField(blank=True, choices=[('account_number', 'Account Number'), ('outstanding_amount', 'Outstanding Amount'), ('overdue_amount', 'Overdue Amount'), ('days_in_arrears', 'Days in Arrears'), ('loan_classification', 'Loan Classification'), ('account_status_code', 'Account Status Code')], max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='update.uploadsession')),
            ],
            options={
                'unique_together': {('session', 'original_header')},
            },
        ),
    ]
