# Generated by Django 5.2.5 on 2026-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_mappingtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='rejected_file',
            field=models.FileField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='rows_rejected',
            field=models.IntegerField(default=0),
        ),
    ]
