# Generated by Django 5.2.5 on 2026-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_uploadsession_rejected_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaneddata',
            old_name='outstanding_amount',
            new_name='CurrentBalanceAmt',
        ),
        migrations.RenameField(
            model_name='cleaneddata',
            old_name='days_in_arrears',
            new_name='months_in_arrears',
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='target_column',
            field=models.CharField(blank=True, choices=[('account_number', 'Account Number'), ('CurrentBalanceAmt', 'Current Balance Amount'), ('overdue_amount', 'Overdue Amount'), ('months_in_arrears', 'Months in Arrears'), ('loan_classification', 'Loan Classification'), ('account_status_code', 'Account Status Code')], max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('pending_mapping', 'Pending Mapping'), ('processing', 'Processing'), ('processed', 'Processed'), ('uploaded', 'Uploaded to SQL'), ('error', 'Error')], default='pending_mapping', max_length=20),
        ),
    ]
