# Generated by Django 5.2.5 on 2026-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_rename_outstanding_amount_cleaneddata_currentbalanceamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='batchupdate_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='generated_script',
            field=models.FileField(blank=True, null=True, upload_to='generated_scripts/'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
