# Generated by Django 5.2.5 on 2026-04-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_uploadsession_batchupdate_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='target_column',
            field=models.CharField(blank=True, choices=[('account_number', 'AccountNo'), ('CurrentBalanceAmt', 'CurrentBalanceAmt'), ('overdue_amount', 'OverdueAmount'), ('months_in_arrears', 'MonthsInArrears'), ('loan_classification', 'LoanClassification'), ('account_status_code', 'AccountStatusCode')], max_length=50),
        ),
    ]
