# Generated by Django 5.2.5 on 2026-04-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0008_subscriber_subscribertoken_usersubscriberprofile_uploadsession_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSubscriber',
            fields=[
                ('subscriber_id', models.IntegerField(db_column='SubscriberID', primary_key=True, serialize=False)),
                ('subscriber_name', models.CharField(db_column='SubscriberName', max_length=500)),
            ],
            options={
                'db_table': 'sheet1',
                'ordering': ['subscriber_name'],
                'managed': False,
            },
        ),
    ]
