# Generated by Django 5.2.13 on 2026-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0011_move_models_to_acctmgt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmapping',
            name='target_column',
            field=models.CharField(blank=True, choices=[('account_number', 'AccountNo'), ('CurrentBalanceAmt', 'CurrentBalanceAmt'), ('overdue_amount', 'AmountOverdue'), ('months_in_arrears', 'MonthsInArrears'), ('loan_classification', 'LoanClassification'), ('account_status_code', 'AccountStatusCode')], max_length=50),
        ),
    ]
