# Generated by Django 6.0.5 on 2026-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0012_alter_columnmapping_target_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='upload_to_db',
            field=models.BooleanField(default=True),
        ),
    ]
