# Generated by Django 6.0.6 on 2026-08-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0013_uploadsession_upload_to_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('pending_mapping', 'Pending Mapping'), ('processing', 'Processing'), ('processed', 'Processed'), ('uploading_to_db', 'Uploading to DB'), ('uploaded', 'Uploaded to SQL'), ('error', 'Error')], default='pending_mapping', max_length=20),
        ),
    ]
