# Generated by Django 6.0.6 on 2026-09-04 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0014_alter_uploadsession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='upload_to_db',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DroppedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='drop_folder/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('dropped_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Import'), ('imported', 'Imported'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_drops', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dropped_at'],
            },
        ),
    ]
